title: Katrin Snell | Pet Portrait and Wildlife Artist
baseurl: /
permalink: '/:title/'
layout_style: grid
palette: black
header:
  has_nav: true
  logo_img: ''
  title: Katrin Snell
footer:
  content: >-
    &copy; Pet Portrait and Wildlife Artist by Katrin Snell. All rights
    reserved.
  has_social: true
  links:
    - new_window: true
      text: Pet Portrait and Wildlife Artist by Katrin Snell
      url: 'https://katrinsnellartist.co.uk/'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
